### ISSUE TITLE
how to use the trained .tar output from pytorch

### ISSUE THREAD

**Issue by eejlny** [Xilinx/LSTM-PYNQ#6]
Hello,

I have used the framework available in https://github.com/Xilinx/pytorch-ocr  to trained a quantized network and this has produced a .tar output. 

I would like to know how can I transform the contents of this tar file with weight/bias parameters to use them here. I can see that the parameters are set in r_model_fw_rw.hpp but how can I get these parameters from the output of the training process ?

For example depending on the number of PE/SIMD the way the parameters are loaded changes as well.

Thanks,

**Comment by ussamazahid96** [comment]
You can export the trained model from .tar using

`python main.py -i <path to .tar> -p <path to quantized parameters used for training> --export`

but do compare the generated r_fw_bw file with the one given in this repo for a few parameters e.g. `NUMBER_OF_NEURONS_TYPEWIDTH, HEIGHT_IN_PIX_TYPEWIDTH `.

**Comment by eejlny** [comment]
OK, thanks for the answer. Unfortunately it is not working for me with the example provided for W2B8A4.

I did 
python main.py --no_cuda -i /hdd1/eejlny/projects/LSTM-BNN-TRAIN/pytorch-quantization/warp-ctc/pytorch_binding/pytorch-ocr/experiments/20190516_085415_QLSTM128_W2B8A4IA32_FC_W32B32/checkpoints/epoch_4000.tar -p /hdd1/eejlny/projects/LSTM-BNN-TRAIN/pytorch-quantization/warp-ctc/pytorch_binding/pytorch-ocr/quantized_params/QLSTM128_W2B8A4I32_FC_W32B32.json --export

It seems to run for  a  bit then I get an exception as below. I did a bit of debugging to try to see what could be wrong and add some "prints".  the float inputs seem OK but then this function to_int is called that raises the exception but I do not know why. I have attached the inputs tar and json. Could you try if it works for you ?

[to_int.zip](https://github.com/Xilinx/LSTM-PYNQ/files/3216337/to_int.zip)



calling to_int
the float weight input is
-0.0783613026 0.2314253449 0.2550106347  ...  0.2614499629 0.2227743268 0.3392964602
-0.3980179131 0.3079786003 0.2402267158  ...  -0.1605570465 -0.1670258939 -0.1657750756
-0.2123548687 0.2293669283 0.1871365011  ...  0.1738871932 -0.0568856634 0.2023661733
          ...             ⋱             ...
-0.2628615797 0.0385836139 0.1232222170  ...  0.0687232092 -0.1102901399 -0.1657559127
-0.1209577098 0.3521865904 0.2046997696  ...  0.0850568190 -0.1823084354 0.0764477998
0.2049286664 -0.2861393094 -0.1318069547  ...  -0.1235941052 0.1995265484 0.0785836205
[torch.FloatTensor of size 128x164]

calling to_int
wrong to_int
Traceback (most recent call last):
  File "main.py", line 156, in <module>
    trainer.export_model(args.simd_factor, args.pe)
  File "/hdd1/eejlny/projects/LSTM-BNN-TRAIN/pytorch-quantization/warp-ctc/pytorch_binding/pytorch-ocr/ocr/trainer.py", line 414, in export_model
    self.model.export(os.path.join(self.output_dir_path, 'r_model_fw_bw.h'), simd_factor, pe)
  File "/hdd1/eejlny/projects/LSTM-BNN-TRAIN/pytorch-quantization/warp-ctc/pytorch_binding/pytorch-ocr/ocr/model.py", line 191, in export
    fc_weight_decl, fc_weight_string = self.batch_norm_fc.linear.hls_weight_string(self.reduce_factor)
  File "/hdd1/eejlny/projects/LSTM-BNN-TRAIN/pytorch-quantization/quantization/modules/quantized_linear.py", line 77, in hls_weight_string
    return quantized_linear_hls_weight_string(weight, self.weight_quantization_scheme, hls_var_name)
  File "/hdd1/eejlny/projects/LSTM-BNN-TRAIN/pytorch-quantization/quantization/function/quantized_linear.py", line 46, in quantized_linear_hls_weight_string
    int_weight = quantization_scheme.to_int(weight).numpy().astype(int)
  File "/hdd1/eejlny/projects/LSTM-BNN-TRAIN/pytorch-quantization/quantization/function/quantization_impl.py", line 40, in to_int
    raise Exception
Exception
